[book]
authors = ["Ankitects Pty Ltd and contributors"]
language = "it"
multilingual = false
src = "src"
title = "Manuale di Anki"

[build]
create-missing = true

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
git-repository-url = "https://github.com/tekinosman/anki-manual-it"
additional-css = ["css/misc.css", "css/kbd.css"]

[output.linkcheck]
optional = true
warning-policy = "warn"
follow-web-links = true
exclude = [
  'microsoft.com',
  'twitter.com',
  'stackexchange.com',
  'stackoverflow.com',
  'https://github.com/open-spaced-repetition/fsrs4anki#add-on-compatibility',
  'support.google.com',
  'https://wikiwiki.jp/rage2050/',
]

[output.html.fold]
enable = true
level = 0
